// Code Generated by Sidekick is for learning and experimentation purposes only.
package gym;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

enum MembershipStatus {
    BRONZE,
    SILVER,
    GOLD
}

class Workout {
    private int id;
    private int startTime;
    private int endTime;

    public Workout(int id, int startTime, int endTime) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public int getId() {
        return id;
    }

    public int getStartTime() {
        return startTime;
    }

    public int getEndTime() {
        return endTime;
    }

    public int getDuration() {
        return endTime - startTime;
    }
}

class Member {
    public int memberId;
    public String name;
    public MembershipStatus membershipStatus;

    public Member(int memberId, String name, MembershipStatus membershipStatus) {
        this.memberId = memberId;
        this.name = name;
        this.membershipStatus = membershipStatus;
    }

    @Override
    public String toString() {
        return "Member ID: " + memberId + ", Name: " + name + ", Membership Status: " + membershipStatus;
    }
}

class Membership {
    public List<Member> members;
    private Map<Integer, List<Workout>> workoutsByMember = new HashMap<>();

    public Membership() {
        members = new ArrayList<>();
    }

    public void addMember(Member member) {
        if (member == null) {
            return;
        }

        for (Member existingMember : members) {
            if (existingMember.memberId == member.memberId) {
                return; // Ignore duplicate member IDs
            }
        }

        members.add(member);
    }

    public void updateMembership(int memberId, MembershipStatus membershipStatus) {
        for (Member member : members) {
            if (member.memberId == memberId) {
                member.membershipStatus = membershipStatus;
                return;
            }
        }
    }

    public MembershipStatistics getMembershipStatistics() {
        int premium = 0;

        for (Member member : members) {
            if (member.membershipStatus == MembershipStatus.GOLD ||
                    member.membershipStatus == MembershipStatus.SILVER) {
                premium++;
            }
        }

        double conversionRate = members.isEmpty() ? 0.0 : (premium * 100.0) / members.size();
        return new MembershipStatistics(members.size(), premium, conversionRate);
    }

    public void addWorkout(Integer memId, Workout wk) {
        if (memId == null || wk == null) {
            return;
        }

        for (Member member : members) {
            if (member.memberId == memId) {
                workoutsByMember.computeIfAbsent(memId, k -> new ArrayList<>()).add(wk);
                return;
            }
        }
        // Ignore if member does not exist
    }

    public Map<Integer, Double> getAverageWorkoutDurations() {
        Map<Integer, Double> avgByMember = new HashMap<>();
           for(Member member : members){
               List<Workout>list = workoutsByMember.get(member.memberId);
               if(list.isEmpty()){
                   avgByMember.put(member.memberId,null);
                   continue;
               }
               double total=0.0;
               for(Workout w : list){
                   total+=w.getDuration();
               }
               avgByMember.put(member.memberId,(total/list.size()));
           }
//        for (Map.Entry<Integer, List<Workout>> entry : workoutsByMember.entrySet()) {
//            List<Workout> workouts = entry.getValue();
//            if (workouts.isEmpty()) {
//                avgByMember.put(entry.getKey(),null);
//                continue;
//            }
//
//            double totalDuration = 0.0;
//            for (Workout workout : workouts) {
//                totalDuration += workout.getDuration();
//            }
//
//            avgByMember.put(entry.getKey(), totalDuration / workouts.size());
//        }

        return avgByMember;
    }

    public Map<Integer, Double> getDuePayments() {
        Map<Integer, Double> dueByMember = new HashMap<>();

        for (Member member : members) {
            switch (member.membershipStatus) {
                case BRONZE:
                    dueByMember.put(member.memberId, calculateDue(member.memberId, 1, 10));
                    break;
                case SILVER:
                    dueByMember.put(member.memberId, calculateDue(member.memberId, 3, 8));
                    break;
                case GOLD:
                    dueByMember.put(member.memberId, calculateDue(member.memberId, 5, 6));
                    break;
            }
        }

        return dueByMember;
    }

    // Kept for compatibility with the existing main/test method name
    public Map<Integer, Double> getPaymentDues() {
        return getDuePayments();
    }

    private double calculateDue(int memberId, int freeLimit, int chargePerHour) {
        List<Workout> workouts = new ArrayList<>(workoutsByMember.getOrDefault(memberId, new ArrayList<>()));

        if (workouts.size() <= freeLimit) {
            return 0.0;
        }

        workouts.sort(Comparator.comparingInt(Workout::getId));

        int totalHours = 0;
        for (int i = freeLimit; i < workouts.size(); i++) {
            int duration = workouts.get(i).getDuration();
            int roundedHours = (duration + 59) / 60; // round up to nearest hour
            totalHours += roundedHours;
        }

        return totalHours * chargePerHour;
    }
}

class MembershipStatistics {
    public int totalMembers;
    public int totalPaidMembers;
    public double conversionRate;

    public MembershipStatistics(int totalMembers, int totalPaidMembers, double conversionRate) {
        this.totalMembers = totalMembers;
        this.totalPaidMembers = totalPaidMembers;
        this.conversionRate = conversionRate;
    }
}

public class Main {
    public static void main(String[] args) {
        testMember();
        testMembership();
        testGetAverageWorkoutDurations();
        testPaymentDue();
        System.out.println("All tests completed.");
    }

    public static void testMember() {
        System.out.println("Running testMember");
        Member testMember = new Member(1, "John Doe", MembershipStatus.BRONZE);

        assert testMember.memberId == 1 :
                "Member ID should be 1, was " + testMember.memberId;
        assert testMember.name.equals("John Doe") :
                "Member name should be \"John Doe\", was \"" + testMember.name + "\"";
        assert testMember.membershipStatus == MembershipStatus.BRONZE :
                "Membership status should be BRONZE, was " + testMember.membershipStatus;
    }

    public static void testMembership() {
        System.out.println("Running testMembership");
        Membership testMembership = new Membership();
        Member testMember = new Member(1, "John Doe", MembershipStatus.BRONZE);
        testMembership.addMember(testMember);

        assert testMembership.members.size() == 1 :
                "Members size should be 1, was " + testMembership.members.size();
        assert testMembership.members.get(0).equals(testMember) :
                "First member should equal testMember";

        testMembership.updateMembership(1, MembershipStatus.SILVER);
        assert testMembership.members.get(0).membershipStatus == MembershipStatus.SILVER :
                "Membership status should be SILVER, was " + testMembership.members.get(0).membershipStatus;

        Member testMember2 = new Member(2, "Alex C", MembershipStatus.BRONZE);
        testMembership.addMember(testMember2);

        Member testMember3 = new Member(3, "Marie C", MembershipStatus.GOLD);
        testMembership.addMember(testMember3);

        Member testMember4 = new Member(4, "Joe D", MembershipStatus.SILVER);
        testMembership.addMember(testMember4);

        Member testMember5 = new Member(5, "June R", MembershipStatus.BRONZE);
        testMembership.addMember(testMember5);

        Member testMember6 = new Member(6, "Westley D", MembershipStatus.SILVER);
        testMembership.addMember(testMember6);

        MembershipStatistics attendanceStats = testMembership.getMembershipStatistics();
        assert attendanceStats.totalMembers == 6 :
                "Total members should be 6, was " + attendanceStats.totalMembers;
        assert attendanceStats.totalPaidMembers == 4 :
                "Total paid members should be 4, was " + attendanceStats.totalPaidMembers;
        assert Math.abs(attendanceStats.conversionRate - 66.67) < 0.1 :
                "Conversion rate should be 66.67, was " + attendanceStats.conversionRate;
    }

    public static void testGetAverageWorkoutDurations() {
        System.out.println("Running testGetAverageWorkoutDurations");
        Membership testMembership = new Membership();

        Member testMember1 = new Member(12, "John Doe", MembershipStatus.SILVER);
        testMembership.addMember(testMember1);

        Member testMember2 = new Member(22, "Alex Cleeve", MembershipStatus.BRONZE);
        testMembership.addMember(testMember2);

        Member testMember3 = new Member(31, "Marie Cardiff", MembershipStatus.GOLD);
        testMembership.addMember(testMember3);

        Member testMember4 = new Member(37, "George Costanza", MembershipStatus.SILVER);
        testMembership.addMember(testMember4);

        Workout testWorkout1 = new Workout(11, 10, 20);
        Workout testWorkout2 = new Workout(24, 15, 35);
        Workout testWorkout3 = new Workout(32, 45, 90);
        Workout testWorkout4 = new Workout(47, 100, 155);
        Workout testWorkout5 = new Workout(56, 120, 200);
        Workout testWorkout6 = new Workout(62, 300, 400);
        Workout testWorkout7 = new Workout(78, 1000, 1010);
        Workout testWorkout8 = new Workout(80, 1010, 1045);

        testMembership.addWorkout(12, testWorkout1);
        testMembership.addWorkout(22, testWorkout2);
        testMembership.addWorkout(31, testWorkout3);
        testMembership.addWorkout(12, testWorkout4);
        testMembership.addWorkout(22, testWorkout5);
        testMembership.addWorkout(31, testWorkout6);
        testMembership.addWorkout(12, testWorkout7);
        testMembership.addWorkout(4, testWorkout8); // not added

        Map<Integer, Double> averageDurations = testMembership.getAverageWorkoutDurations();

        assert Math.abs(averageDurations.get(12) - 25.0) < 0.1 :
                "average duration for member 12 should be 25.0, was " + averageDurations.get(12);
        assert Math.abs(averageDurations.get(22) - 50.0) < 0.1 :
                "average duration for member 22 should be 50.0, was " + averageDurations.get(22);
        assert Math.abs(averageDurations.get(31) - 72.5) < 0.1 :
                "average duration for member 31 should be 72.5, was " + averageDurations.get(31);
        assert !averageDurations.containsKey(4);
    }

    public static void testPaymentDue() {
        System.out.println("Running testPaymentDue");
        Membership testMembership = new Membership();

        Member testMember1 = new Member(12, "John Doe", MembershipStatus.GOLD);
        testMembership.addMember(testMember1);

        Member testMember2 = new Member(22, "Alex Cleeve", MembershipStatus.GOLD);
        testMembership.addMember(testMember2);

        Member testMember3 = new Member(31, "Marie Cardiff", MembershipStatus.GOLD);
        testMembership.addMember(testMember3);

        Workout testWorkout1 = new Workout(11, 10, 20);
        Workout testWorkout2 = new Workout(24, 15, 35);
        Workout testWorkout3 = new Workout(32, 45, 90);
        Workout testWorkout4 = new Workout(47, 100, 155);
        Workout testWorkout5 = new Workout(56, 120, 200);
        Workout testWorkout6 = new Workout(62, 300, 400);
        Workout testWorkout7 = new Workout(78, 1000, 1010);

        testMembership.addWorkout(12, testWorkout1);
        testMembership.addWorkout(12, testWorkout2);
        testMembership.addWorkout(12, testWorkout3);
        testMembership.addWorkout(12, testWorkout4);
        testMembership.addWorkout(12, testWorkout5);
        testMembership.addWorkout(12, testWorkout6);
        testMembership.addWorkout(12, testWorkout7);

        Map<Integer, Double> paymentDues = testMembership.getDuePayments();

        assert Math.abs(paymentDues.get(12) - 18.0) < 0.1 :
                "Payment due for member 12 should be 18.0, was " + paymentDues.get(12);
        assert Math.abs(paymentDues.get(22) - 0.0) < 0.1 :
                "Payment due for member 22 should be 0.0, was " + paymentDues.get(22);
        assert Math.abs(paymentDues.get(31) - 0.0) < 0.1 :
                "Payment due for member 31 should be 0.0, was " + paymentDues.get(31);
    }
}
